[package]
name = "lukasbrot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
num-bigint = "0.4.5"
num = "0.4.3"

[dependencies.web-sys]
version = "0.3.69"
features = [
  'ImageData',
  'CanvasRenderingContext2d',
  'console',
]
